// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACdeffa278E69hPbghmB0nxyQ7ZRT7r08',
    appId: '1:912220333816:web:95e0cf03ba79d99f8bbd0d',
    messagingSenderId: '912220333816',
    projectId: 'recordmanagementsystem-23068',
    authDomain: 'recordmanagementsystem-23068.firebaseapp.com',
    storageBucket: 'recordmanagementsystem-23068.appspot.com',
    measurementId: 'G-RKL7XT5ZST',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0cQXweu7NPaIFXX6ybhJ34rQgtHlSwBQ',
    appId: '1:912220333816:android:b9ab8f99c5fab4808bbd0d',
    messagingSenderId: '912220333816',
    projectId: 'recordmanagementsystem-23068',
    storageBucket: 'recordmanagementsystem-23068.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-YxDmuZEjOIIC64kVp15e4oFK_DfunZ0',
    appId: '1:266289039385:ios:abf0bba72cb0b34a5f4288',
    messagingSenderId: '266289039385',
    projectId: 'recordmanagementsystem-131ec',
    storageBucket: 'recordmanagementsystem-131ec.appspot.com',
    iosBundleId: 'com.example.recordManagementSystem',
  );
}